name: Base Image CI

on:
  push:
    paths:
      - '.github/workflows/base-image.yml'
      - 'tools/**'
    branches: [ image_build ]
  pull_request:
    paths:
      - '.github/workflows/base-image.yml'
      - 'tools/**'
    branches: [ image_build ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE=oren12321/image-tools
          echo ::set-output name=latest_image::${IMAGE}:latest
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: tools
          file: tools/Dockerfile
          push: false
          tags: ${{ steps.prep.outputs.tagged_image }},${{ steps.prep.outputs.latest_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test
        run: |
          docker run --rm --privileged --env-file tools/env.list --volume ~/workdir:/workdir ${{ steps.prep.outputs.tagged_image }} ./create_custom_base_image_tarball.sh

      - name: Clean
        if: always()
        run: |
          sudo rm -rf ~/workdir

