name: Docker Image CI

on:
  push:
    paths:
      - '.github/workflows/sample-docker.yml'
      - 'sample-docker/**'
    branches: [ main ]

jobs:
  sample-docker-build:

    runs-on: ubuntu-18.04

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Checkout code
        uses: actions/checkout@v2

      - 
        name: Build and (not) push
        uses: docker/build-push-action@v2
        with:
          context: sample-docker
          file: sample-docker/Dockerfile
          push: false
          tags: user/sample-docker:latest
          platforms: linux/arm64

