name: Sample App CI

on:
  push:
    paths:
      - '.github/workflows/sample-app.yml'
      - 'sample-app/**'
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/sample-app.yml'
      - 'sample-app/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE=oren12321/sample-app
          echo ::set-output name=latest_image::${IMAGE}:latest
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: sample-app
          file: sample-app/Dockerfile
          push: false
          platforms: linux/arm64
          tags: ${{ steps.prep.outputs.tagged_image }},${{ steps.prep.outputs.latest_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

